### ISSUE TITLE
`dedup: false` in collection doesn't work?

### ISSUE THREAD

**Issue by everpeace** [google/triage-party#122]
I set 

```
collections:
  id: foo
  dedup: false
  rules:
  - rule-a
```

however,  the output of rule `rule-a` in the collection `foo`  looks like dedeup-ed

![image](https://user-images.githubusercontent.com/608782/83328850-11d85700-a2c1-11ea-9816-85e28f4c4b9d.png)

Is this behavior expected?
