### ISSUE TITLE
Tie repo to collection

### ISSUE THREAD

**Issue by eddiezane** [google/triage-party#262]
I'm (finally) starting to build out the rules for sig-cli.

We're looking to have one Triage Party instance with a collection per repository we maintain.

Currently to accomplish this we need to a rule per collection/repo resulting in nearly identical rules.

```
collections:
  - id: kubectl
    name: Kubectl Triage
    rules:
      - new-kubectl-issue-needs-triage
  - id: kubernetes-daily
    name: Kubernetes Triage
    rules:
      - new-kubernetes-issue-needs-triage

rules:
  new-kubectl-issue-needs-triage:
    name: "New Kubectl issues that need triage"
    resolution: "Apply a triage label"
    type: issue
    repos:
      - https://github.com/kubernetes/kubectl
    filters:
      - label: "needs-triage"
      - label: "sig/cli"
      - created: -7d
  new-kubernetes-issue-needs-triage:
    name: "New Kubernetes issues that need triage"
    resolution: "Apply a triage label"
    type: issue
    repos:
      - https://github.com/kubernetes/kubernetes
    filters:
      - label: "needs-triage"
      - label: "sig/cli"
      - created: -7d
```

I'd like to have a single rule and then scope each collection to a repo.

```
collections:
  - id: kubectl
    name: Kubectl Triage
    repos:
      - https://github.com/kubernetes/kubectl
    rules:
      - new-issue-needs-triage
  - id: kubernetes-daily
    name: Kubernetes Triage
    repos:
      - https://github.com/kubernetes/kubernetes
    rules:
      - new-issue-needs-triage

rules:
  new-issue-needs-triage:
    name: "New issues that need triage"
    resolution: "Apply a triage label"
    type: issue
    filters:
      - label: "needs-triage"
      - label: "sig/cli"
      - created: -7d
```

I can take a stab at implementing this if you think it makes sense.
