### ISSUE TITLE
Excluding issues by project members/contributors/collaborators

### ISSUE THREAD

**Issue by meltsufin** [google/triage-party#264]
I'm trying to create a rule that would show issues that have been last updated by non-project members. It doesn't seem to work using my attempts.

For example the following filter still seems to include issues that were filed by a committer and have no comments.
```
    type: issue
    filters:
      - tag: "!member-last"
      - tag: "!contributor-last"
      - tag: "!collaborator-last"
```
