### ISSUE TITLE
FR: filter for multiple labels of a type

### ISSUE THREAD

**Issue by joeyparrish** [google/triage-party#274]
My projects have "type" labels such as "type: bug" and "type: enhancement".  I would like to be able to filter for issues with multiple of these.  This is not currently possible as far as I can tell for more than two type labels.

For two labels that are mutually exclusive, this is still doable with the current filter system:

```yaml
  filters:
    # Match issues with more than one "type" label
    - label: "type: bug"
    - label: "type: enhancement"
```

But I don't believe this is possible with this structure and three or more type labels.

One way to solve it would be a filter that runs over all labels concatenated (maybe with some separator like a newline that can't appear in labels).  For example, then I could do something like this:

```yaml
  filters:
    # Match issues with more than one "type" label
    - all-labels: ".*type: .*type: .*"
```

Another solution might be to have a counter for labels matching a certain regex.  For example:

```yaml
  filters:
    # Match issues with more than one "type" label
    - label-count:
      - regex: "type: .*"
      - match: ">1"
```

I'm open to other ideas, and I'd be happy with any solution the maintainers would be willing to accept.
